import type { Metadata } from "next";
import { Inter } from "next/font/google";
import UserAvatar from "@/components/UserAvatar";
import { auth, signIn, signOut } from "@/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex justify-between p-7 border-b-[1px] bg-slate-200 align-middle">
          <h1 className="red font-bold text-3xl">Quick Cart Admin Panel</h1>
          {session?.user ? (
            <form
              action={async () => {
                "use server";
                await signOut();
              }}
              className="flex gap-4"
            >
              <button className="bg-blue-400 hover:bg-blue-500 rounded-full text-cyan-50 font-bold py-2 px-4">
                Signout
              </button>
              <UserAvatar />
            </form>
          ) : (
            <form
              action={async () => {
                "use server";
                await signIn("google");
              }}
            >
              <button
                className="bg-blue-400 hover:bg-blue-500 rounded-full text-cyan-50 font-bold py-2 px-4"
                type="submit"
              >
                Sign In
              </button>
            </form>
          )}
        </div>
        {children}
      </body>
    </html>
  );
}
