import type { Metadata } from "next";
import { Inter } from "next/font/google";
import UserAvatar from "@/components/UserAvatar";
import { auth, signIn, signOut } from "@/auth";
import { redirect } from "next/navigation";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  if (!session?.user) {
    redirect("/login");
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex justify-between px-4 py-2 shadow-md border-b-[1px] bg-slate-200 items-center">
          <h1 className="red font-bold text-3xl">Quick Cart Admin Panel</h1>
          {session?.user && (
            <form
              action={async () => {
                "use server";
                await signOut();
              }}
              className="flex gap-4"
            >
              <button className="bg-blue-400 hover:bg-blue-500 rounded-full text-cyan-50 font-bold py-1 px-4">
                Signout
              </button>
              <UserAvatar />
            </form>
          )}
        </div>
        <div className="flex gap-6">
          <div className="flex flex-col w-1/6 h-screen bg-slate-600">
            <div className="flex gap-2 mt-1 mx-6 hover:bg-slate-500 px-3 py-3 rounded-lg cursor-pointer">
              <Image src={'/Pictures/inventory_2_26dp_E8EAED_FILL0_wght400_GRAD0_opsz24.png'} alt="Inventory" width={25} height={25} />
              <div className="font-semibold text-stone-100">Products</div>
            </div>
            <div className="flex gap-2 mt-1 mx-6 hover:bg-slate-500 px-3 py-3 rounded-lg cursor-pointer">
              <Image src={'/Pictures/stack_star_26dp_E8EAED_FILL0_wght400_GRAD0_opsz24.png'} alt="Inventory" width={25} height={25} />
              <div className="font-semibold text-stone-100">Featured Product</div>
            </div>
            <div className="flex gap-2 mt-1 mx-6 hover:bg-slate-500 px-3 py-3 rounded-lg cursor-pointer">
              <Image src={'/Pictures/group_26dp_E8EAED_FILL0_wght400_GRAD0_opsz24.png'} alt="Inventory" width={25} height={25} />
              <div className="font-semibold text-stone-100">Users</div>
            </div>
          </div>
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
